import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text
import hashlib
import os
from dotenv import load_dotenv

def get_hash_id(name):
    """Normalizing artist data and generating unique IDs"""
    if pd.isna(name):
        return None
    return hashlib.md5(str(name).strip().encode('utf-8')).hexdigest()[:15]

def run_etl(file_path, db_url):
    print("ETL Pipeline start")
    
    # 1. EXTRACT
    print("dataset.csv reading")
    df = pd.read_csv(file_path)
    
    # 2. TRANSFORM
    print("data cleaning")
    
    # remove rows where important fields are empty.
    df = df.dropna(subset=['track_id', 'track_name', 'artists', 'album_name'])
    
    # remove repeated songs (track_id)
    df = df.drop_duplicates(subset=['track_id'])
    
    # restrict values ​​according to the database's CHECK constraints.
    df['popularity'] = df['popularity'].clip(0, 100)
    df['danceability'] = df['danceability'].clip(0.0, 1.0)
    df['energy'] = df['energy'].clip(0.0, 1.0)
    df['duration_ms'] = df['duration_ms'].apply(lambda x: x if x > 0 else 1)
    
    # PostgreSQL connect
    engine = create_engine(db_url)
    
    # 3. LOAD
    
    # table 1 - Genres
    print("'genres' fil")
    genres_df = pd.DataFrame({'genre_name': df['track_genre'].unique()})
    with engine.connect() as conn:
        for _, row in genres_df.iterrows():
            conn.execute(
                text("INSERT INTO genres (genre_name) VALUES (:genre) ON CONFLICT (genre_name) DO NOTHING"),
                {"genre": row['genre_name']}
            )
            conn.commit()
    
    # get the genre_ids generated by the database
    with engine.connect() as conn:
        db_genres = pd.read_sql("SELECT genre_id, genre_name FROM genres", conn)
    genre_map = dict(zip(db_genres['genre_name'], db_genres['genre_id']))
    
    # table 2 - Albums
    print("'albums' fil")
    albums_df = pd.DataFrame({'album_name': df['album_name'].unique()})
    with engine.connect() as conn:
        for _, row in albums_df.iterrows():
            conn.execute(
                text("INSERT INTO albums (album_name) VALUES (:album) ON CONFLICT DO NOTHING"),
                {"album": row['album_name']}
            )
            conn.commit()
            
    with engine.connect() as conn:
        db_albums = pd.read_sql("SELECT album_id, album_name FROM albums", conn)
    album_map = dict(zip(db_albums['album_name'], db_albums['album_id']))
    
    # table 3 Artists & Many-to-Many connection
    print(" 'artists' and 'track_artists' develop")
    artists_set = set()
    track_artists_rows = []
    
    for _, row in df.iterrows():
        t_id = row['track_id']
        # separate artists if they sing the song with several people (Ingrid Michaelson;ZAYN)
        track_artists = [a.strip() for a in str(row['artists']).split(';')]
        for artist_name in track_artists:
            a_id = get_hash_id(artist_name)
            artists_set.add((a_id, artist_name))
            track_artists_rows.append({'track_id': t_id, 'artist_id': a_id})
            
    artists_df = pd.DataFrame(list(artists_set), columns=['artist_id', 'artist_name']).drop_duplicates(subset=['artist_id'])
    with engine.connect() as conn:
        for _, row in artists_df.iterrows():
            conn.execute(
                text("INSERT INTO artists (artist_id, artist_name) VALUES (:id, :name) ON CONFLICT (artist_id) DO NOTHING"),
                {"id": row['artist_id'], "name": row['artist_name']}
            )
            conn.commit()
    
    # table 4 - Tracks (Main Fact Table)
    print("fil main 'tracks' ")
    df['genre_id'] = df['track_genre'].map(genre_map)
    df['album_id'] = df['album_name'].map(album_map)
    
    tracks_columns = [
        'track_id', 'track_name', 'album_id', 'genre_id', 'popularity', 'duration_ms',
        'explicit', 'danceability', 'energy', 'key', 'loudness', 'mode', 
        'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature'
    ]
    tracks_df = df[tracks_columns]
    
    with engine.connect() as conn:
        for _, row in tracks_df.iterrows():
            conn.execute(
                text("""
                    INSERT INTO tracks (track_id, track_name, album_id, genre_id, popularity, duration_ms, explicit, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, time_signature) 
                    VALUES (:track_id, :track_name, :album_id, :genre_id, :popularity, :duration_ms, :explicit, :danceability, :energy, :key, :loudness, :mode, :speechiness, :acousticness, :instrumentalness, :liveness, :valence, :tempo, :time_signature) 
                    ON CONFLICT (track_id) DO NOTHING
                """),
                row.to_dict()
            )
            conn.commit()
    
    # populating the intermediate table of the Many-to-Many relationship
    track_artists_df = pd.DataFrame(track_artists_rows).drop_duplicates()
    with engine.connect() as conn:
        for _, row in track_artists_df.iterrows():
            conn.execute(
                text("INSERT INTO track_artists (track_id, artist_id) VALUES (:track_id, :artist_id) ON CONFLICT DO NOTHING"),
                {"track_id": row['track_id'], "artist_id": row['artist_id']}
            )
            conn.commit()
    
    print("done, datas are in postgresql ")

if __name__ == "__main__":
    current_dir = os.path.dirname(__file__)
    dotenv_path = os.path.join(current_dir, '..', '.env')
    
    
    load_dotenv(dotenv_path=dotenv_path, override=True)
    
    CSV_FILE_PATH = os.getenv("CSV_FILE_PATH")
    DATABASE_URL = os.getenv("DATABASE_URL")
    
    
    if not CSV_FILE_PATH:
        CSV_FILE_PATH = "/Users/allamakaryan/Desktop/spotify_project/data/dataset.csv"
        
    if not DATABASE_URL:
        DATABASE_URL = "postgresql://postgres:MY_PASSWORD@localhost:5432/postgres"
    
    run_etl(CSV_FILE_PATH, DATABASE_URL)